### ISSUE TITLE
Elmish.HMR 3.0.2 doesn't work with Fable 2.x on RN

### ISSUE THREAD

**Issue by forki** [elmish/hmr#19]
![screenshot_20190226-130050](https://user-images.githubusercontent.com/57396/53411880-0dd7ce00-39c8-11e9-86ca-fb068ed26406.jpeg)

Note: we don't use webpack here but React Native's own bundler. But this worked so far.

/cc @MangelMaxime

**Comment by forki** [comment]
It looks like the `hot` module is actually found, but it only has `accept` as single method defined. This is also described here: https://facebook.github.io/react-native/blog/2016/03/24/introducing-hot-reloading#hmr-api

I assume we should check if `addDisposeHandler` is defined an otherwise don't call it

**Comment by MangelMaxime** [comment]
If we don't have accept to `addDisposeHandler`, then it's a problem because we can't stop the old program.

We need to create a "polyfill" for it.

If we detect that `addDisposeHandler` doesn't exist, we could trigger a custom `event` [here](https://github.com/elmish/hmr/blob/master/src/hmr.fs#L27-L31).

And then listen to the custom event [here)(https://github.com/elmish/hmr/blob/master/src/hmr.fs#L84-L88) if `addDisposeHandler` doesn't exist.

I would create two functions:
- `triggerCustomDispose hot`: if `hot.addDisposeHandler === undefined` -> trigger custom event
- `onDisposeHandler hot`:
  - if `hot.addDisposeHandler === undefined` -> listen to custom event
  - if `hot.addDisposeHandler !== undefined` -> use to the standard `hot.addDisposeHandler`

**Comment by forki** [comment]
that sounds like a good plan. would love to test it

**Comment by MangelMaxime** [comment]
> that sounds like a good plan. would love to test it

Yes, but what I said is partially wrong 😅

`hot.addDisposeHandler` is called before the new application takes place because it's used to pass the oldState to the new application. 

I am taking a look at the issue and will release a beta when ready.

**Comment by MangelMaxime** [comment]
I think I have a lead.

According to the [master](https://github.com/facebook/metro/blob/master/packages/metro/src/lib/polyfills/require.js#L30-L35) branch of metro  `hot` should have these properties:

```js
type HotModuleReloadingData = {|
  acceptCallback: ?HotModuleReloadingCallback,
  accept: (callback: HotModuleReloadingCallback) => void,
  disposeCallback: ?HotModuleReloadingCallback,
  dispose: (callback: HotModuleReloadingCallback) => void,
|};
```

But when I take a look at the file in my local project, I get:

```js
type HotModuleReloadingData = {|
  acceptCallback: ?HotModuleReloadingAcceptFn,
  accept: (callback: HotModuleReloadingAcceptFn) => void,
|};
```

So I look at the blame history of the `require.js` polyfill and discover that since version v0.29+ they have implemented the `dispose` feature for HMR. [Commit](https://github.com/facebook/metro/commit/edacc36cb41515db860f7fab6d4b455e6f4bf26c)

Because `metro` is included as a dependency of react-native. I am upgrading SAFE Nightwatch to the latest version of react native. And will continue to work from there as I should now have access to `dispose` function which is an alias to `addDisposeHandler`.

*Seems like I manage to upgrade to latest react native* However, I needed to update the android/gradle project too. I will create a dedicated PR to SAFE Nightwatch so you can have a look at it.

**Comment by forki** [comment]
My production app already is on latest RN and still has this problem

Maxime Mangel <notifications@github.com> schrieb am Mi., 27. Feb. 2019,
12:37:

**Comment by MangelMaxime** [comment]
I didn't tested Elmish.HMR yet (time to eat^^).

But at least, I now see `dispose` handler.
<img width="542" alt="capture d ecran 2019-02-27 a 12 50 54" src="https://user-images.githubusercontent.com/4760796/53488394-67a2cb80-3a8e-11e9-9e93-410f1bb38ca6.png">

And this is normal if you still have the error with the current version of Elmish.HMR it's using `addDisposeHandler`. 

The things that suprise me is that in their definition file is that `type HotModuleReloadingCallback = ()=> void;` doesn't receive an argument. But I will see, if `dispose` is called as expected I can find a way to distribute the `oldState` in another way.

**Comment by MangelMaxime** [comment]
So it seems `dispose` is called when expected. I am working on a way to detect if the platform is ReactNative in order to pass the state using another mechanism because ReactNative doesn't give access to a `data` from `dispose` in order to pass information between instances.

**Comment by MangelMaxime** [comment]
HMR is working locally :)

The HMR is slow when recording the GIF but without the GIF recorder with are under the second.

![2019-02-27 17 38 03](https://user-images.githubusercontent.com/4760796/53506594-8f0d8e80-3ab6-11e9-8235-08abf9964677.gif)

I will port the local code to Elmish.HMR this evening and will notify you when it's available as I also need to check I didn't break browser support.

**Comment by forki** [comment]
Wow. Awesomeness

Maxime Mangel <notifications@github.com> schrieb am Mi., 27. Feb. 2019,
17:40:

**Comment by MangelMaxime** [comment]
Fix released in version 3.2.0

I am preparing the PR for Nightwatch. You will decide to merge it or no. :)

**Comment by MangelMaxime** [comment]
The fix will work only for the version of RN/Metro which implements the `dispose` function. This is a requirement to make the HMR works properly.

**Comment by forki** [comment]
It works like a charme and I think it's much faster with fable2 than before.
This is amazing work! Thanks so much!!!
