### ISSUE TITLE
unable to get HMR working for SAFE-Nightwatch

### ISSUE THREAD

**Issue by ctaggart** [elmish/hmr#6]
I can't get HMR working with the SAFE-Nightwatch demo app: https://github.com/SAFE-Stack/SAFE-Nightwatch/issues/50. I provided a YouTube video. I also tried updating Gradle, the Android plugin, and React Native without luck.

**Comment by MangelMaxime** [comment]
@forki Did you get HMR working with RN ?

Last time I heard about it, we was not able to support it. Is it still the case ?

**Comment by forki** [comment]
yes HMR worked fine. but something broke very recently. I'm bisecting rigth now. see that other issue

**Comment by forki** [comment]
ok this can be closed.  found the root cause.

**Comment by forki** [comment]
one questio is: can we make lazyView2 work with HMR? In other words could the HMR module hijack that function and make it non-lazy? // @et1975

**Comment by MangelMaxime** [comment]
@forki Someone that here https://github.com/fable-elmish/react/issues/22

I am not sure of the direction to take.

IMO, if someone need to use `lazyView` then even in dev mode we need to have it active otherwise how would you check the final user experience.

But as I don't use them (yet), I don't have a lot of experience with it..
